#!/usr/bin/perl

use strict;
use esmith::Build::CreateLinks qw(:all);

#--------------------------------------------------
## example of what is a createlinks
##--------------------------------------------------


#mandatory to create db after installation
my $event = 'nethserver-zabbix-update';
event_actions ($event,
     'initialize-default-databases' => '00',
     'nethserver-zabbix-conf' => '20',
     'nethserver-zabbix-conf-db' => '30'
);

templates2events("/etc/httpd/conf.d/zabbix.conf", $event);
#templates2events("/etc/zabbix/zabbix_server.conf", $event);
#templates2events("/etc/zabbix/web/zabbix.conf.php", $event);
templates2events("/var/lib/pgsql/data/pg_hba.conf", $event);

#example 1

#launch several actions following one event
# number < 10 -> action start before template expand
# number < 90 -> action start after template expansion
# number > 90 < 100 -> action starts after the service restart
#event_actions($event, qw(
#             nethserver-zabbix-conf 20
#));
#expand templates following one event
#event_templates($event, qw(
#                /etc/httpd/conf.d/virtualhosts.conf
#                /etc/Other/Path
#));
#restart services following one event
event_services($event,
               'zabbix-server' => 'restart',
               'zabbix-agent' => 'restart',
               'httpd' => 'reload'
);

#example2 when you have several events with several 
#templates,actions,services to manage


#templates expand following several events
#foreach (qw(sysconfig/nfs exports /etc/otherPath /other/path))
#{
#    templates2events("/etc/$_", qw(
#    nethserver-nfs-update
#    other-event-name
#    event-name
#    ));
#}

#Template to expand following several events
#foreach (qw(exports))
#{
#    templates2events("/etc/$_", qw(
#    interface-update
#    ibay-create
#    ibay-delete
#    ibay-modify
#    ));
#}

#it could be also
#templates2events("/etc/exports",qw(
#    interface-update
#    ibay-create
#    ibay-delete
#    ibay-modify
#    ));



#restart services following one event
#foreach $event (qw(nethserver-nfs-update))
#{
#    event_services($event,
#        'nfs-lock' => 'restart', 
#        'nfs' => 'restart',
#        'rpcbind' => 'restart' );
#}


#launch an action following several events
# number < 10 -> action start before template expand
# number < 90 -> action start after template expansion
# number > 90 < 100 -> action starts after the service restart

#for $event (qw(nethserver-nfs-update interface-update ibay-create ibay-delete ibay-modify))
#{
#    event_actions ($event, 'nethserver-name-Action' => '95');
#    event_actions ($event, 'nethserver-Other-Action' => '95');
#}
