#!/usr/bin/perl

use strict;
use esmith::Build::CreateLinks qw(:all);

#--------------------------------------------------
## example of what is a createlinks
##--------------------------------------------------


#mandatory to create db after installation
my $event = 'nethserver-zabbix-update';
event_actions ($event,
     'initialize-default-databases' => '00',
     'nethserver-zabbix-conf' => '10',
     'nethserver-zabbix-conf-db' => '90'
);

templates2events("/etc/httpd/conf.d/zabbix.conf", $event);
templates2events("/etc/httpd/conf.d/default-virtualhost.inc", $event);
templates2events("/etc/zabbix/zabbix_server.conf", $event);
templates2events("/etc/zabbix/zabbix_agentd.conf", $event);
templates2events("/etc/zabbix/web/zabbix.conf.php", $event);
templates2events("/var/lib/pgsql/data/pg_hba.conf", $event);
templates2events("/etc/opt/rh/rh-php73/php-fpm.d/zabbix.conf", $event);

#example 1

#launch several actions following one event
# number < 10 -> action start before template expand
# number < 90 -> action start after template expansion
# number > 90 < 100 -> action starts after the service restart
#event_actions($event, qw(
#             nethserver-zabbix-conf 20
#));
#expand templates following one event
#event_templates($event, qw(
#                /etc/httpd/conf.d/virtualhosts.conf
#                /etc/Other/Path
#));
#restart services following one event
event_services($event,
               'zabbix-server' => 'restart',
               'zabbix-agent' => 'restart',
               'httpd' => 'reload',
               'postgresql' => 'restart',
               'rh-php73-php-fpm' => 'restart'
);


#--------------------------------------------------
# actions for pre-backup-data event
#--------------------------------------------------

$event = 'pre-backup-data';

event_actions($event, 'nethserver-zabbix-backup' => 50);

#--------------------------------------------------
# actions for post-restore-data event
#--------------------------------------------------

$event = 'post-restore-data';

event_actions($event, 'nethserver-zabbix-restore' => 50);
event_services($event, 'zabbix-server' => 'restart');
