#!/bin/bash

# create and chown logfiles
#touch /var/log/zabbix/zabbix_agentd.log
#chown zabbix:zabbix /var/log/zabbix/zabbix_server.log /var/log/zabbix/zabbix_agentd.log

# Create DB and user
echo "create role zabbix with CREATEDB LOGIN PASSWORD '$(cat /var/lib/nethserver/secrets/zabbix)'" | sudo -u postgres psql
echo "alter user zabbix with encrypted password '$(cat /var/lib/nethserver/secrets/zabbix)'" | sudo -u postgres psql
echo "create database zabbix owner zabbix" | sudo -u postgres psql

# Set zabbix shell to bash for login as zabbix user to write db
usermod -s /bin/bash zabbix

# Fill DB
zcat $(rpm -ql zabbix-server-pgsql | grep create.sql.gz) | sudo -u zabbix psql zabbix

# Set zabbix shell to /bin/false again for security
usermod -s /bin/false zabbix

# import map images of Andy Wismer
mv /root/zabbiximages /var/lib/pgsql/data/
cd /var/lib/pgsql/data/zabbiximages
for d in *.png; do su postgres -c "psql zabbix postgres -c \"insert into images (imageid,imagetype,name,image) values ((select max(imageid) +1 from images),1,'$d',pg_read_binary_file('zabbiximages/$d'));\""; done

# rename backup monitoring script
mv /usr/local/bin/nethbackup_check /usr/local/bin/nethbackup_check.py
