#!/bin/bash

# create and chown logfiles
#touch /var/log/zabbix/zabbix_agentd.log
#chown zabbix:zabbix /var/log/zabbix/zabbix_server.log /var/log/zabbix/zabbix_agentd.log

# Create DB and user
echo "create role zabbix with CREATEDB LOGIN PASSWORD '$(cat /var/lib/nethserver/secrets/zabbix)'" | sudo -u postgres psql
echo "alter user zabbix with encrypted password '$(cat /var/lib/nethserver/secrets/zabbix)'" | sudo -u postgres psql
echo "create database zabbix owner zabbix" | sudo -u postgres psql

# Set zabbix shell to bash for login as zabbix user to write db
usermod -s /bin/bash zabbix

# Fill DB
zcat $(rpm -ql zabbix-server-pgsql | grep create.sql.gz) | sudo -u zabbix psql zabbix

# Set zabbix shell to /bin/false again for security
usermod -s /bin/false zabbix
